insert into holders (id, name, date, left_child, right_child) values (1, 'holder_001', '2024-01-01', NULL, NULL);
insert into holders (id, name, date, referrer, left_child, right_child) values (3, 'holder_003', '2024-01-01',1, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (2, 'holder_002', '2024-01-01',1, null, null);
UPDATE holders SET left_child=2, right_child=3 WHERE id=1;
insert into holders (id, name, date, referrer, left_child, right_child) values (5, 'holder_005', '2024-01-01',1, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (4, 'holder_004', '2024-01-01',1, null, null);
UPDATE holders SET left_child=4, right_child=5 WHERE id=2;
insert into holders (id, name, date, referrer, left_child, right_child) values (7, 'holder_007', '2024-01-01',3, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (6, 'holder_006', '2024-01-01',3, null, null);
UPDATE holders SET left_child=6, right_child=7 WHERE id=3;
insert into holders (id, name, date, referrer, left_child, right_child) values (8, 'holder_008', '2024-01-01',4, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (9, 'holder_009', '2024-01-01',4, null, null);
UPDATE holders SET left_child=8, right_child=9 WHERE id=4;
insert into holders (id, name, date, referrer, left_child, right_child) values (10, 'holder_010', '2024-01-01',5, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (11, 'holder_011', '2024-01-01',5, null, null);
UPDATE holders SET left_child=10, right_child=11 WHERE id=5;
insert into holders (id, name, date, referrer, left_child, right_child) values (12, 'holder_012', '2024-01-01',1, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (13, 'holder_013', '2024-01-01',6, null, null);
UPDATE holders SET left_child=12, right_child=13 WHERE id=6;
insert into holders (id, name, date, referrer, left_child, right_child) values (14, 'holder_014', '2024-01-01',7, null, null);
insert into holders (id, name, date, referrer, left_child, right_child) values (15, 'holder_015', '2024-01-01',7, null, null);
UPDATE holders SET left_child=14, right_child=15 WHERE id=7;